---
title: "markergenes_vGO"
author: "T Attenborough"
date: "2023-12-08"
output: html_document
---

```{r}
library(Seurat) #Seurat v4.0.2
library(dplyr)
library(patchwork)
library(here)
library(ggplot2)
library(clustree)
library(ggrepel)
library(SeuratDisk)
library(ggpubr)
library(RVenn)
library(readxl)
library(data.table)
library(UpSetR)
library(pheatmap)
#sessionInfo()
library(stringr)
library(tidyverse)

```
oImport sporocyst 
```{r}
sporocysts_df <- read.csv("/Users/ta13/R_git/topgo_tutorial/sporo_longlist_0.7/topGO_grouped_longlist_0.7_withCC.csv", stringsAsFactors = FALSE, header = TRUE) #import the marker data from somule papaer
```

oImport sporocyst 
```{r}
neuronMarkers <- read.csv("markergene_compara/mira_sporo_somule_adult_compare_Neuron_markers30.csv") #import the marker data from somule papaer
```

```{r}
sporocyst_2genes <- sporocysts_df %>%
  filter(str_detect(genes, ","))
sporocyst_BPonly_2genes <- sporocyst_2genes %>%
  filter(str_detect(Type, "BP"))
```

Find the neuron marker genes in the GO list
```{r}
testdelim <- separate(data = sporocyst_BPonly_2genes, col = genes, into = c("left", "right"))
testdf <- filter(sporocyst_BPonly_2genes, genes %in%  c(allmygenes$sporocyst_neur.gene))

unNestedGO <- sporocyst_BPonly_2genes %>%
    separate_rows(genes, sep=",\\s*")
```

```{r}
neuron_markergenesInGO <- filter(unNestedGO, genes %in%  c(neuronMarkers$sporocyst_neur.gene))
write.csv(x=neuron_markergenesInGO, file="markergene_compara/neuronMarkersInGO.csv") #save this as a csv
```

```{r}
myMarkers <- read.csv("markergene_compara/mira_sporo_somule_adult_compare_Muscle_markers30.csv") #import the marker data from somule papaer
markergenesInGO <- filter(unNestedGO, genes %in%  c(myMarkers$sporocyst_musc.gene))
write.csv(x=markergenesInGO, file="markergene_compara/muscleMarkersInGO.csv") #save this as a csv
```

```{r}
myMarkers <- read.csv("markergene_compara/mira_sporo_somule_adult_compare_Parenchyma_markers30.csv") #import the marker data from somule papaer
markergenesInGO <- filter(unNestedGO, genes %in%  c(myMarkers$sporocyst_paren.gene))
write.csv(x=markergenesInGO, file="markergene_compara/parenchymaMarkersInGO.csv") #save this as a csv
```

```{r}
myMarkers <- read.csv("markergene_compara/mira_sporo_somule_adult_compare_Stem_markers_top30.csv") #import the marker data from somule papaer
markergenesInGO <- filter(unNestedGO, genes %in%  c(myMarkers$sporocyst_stemgerm.gene))
write.csv(x=markergenesInGO, file="markergene_compara/stemMarkersInGO.csv") #save this as a csv
```

```{r}
myMarkers <- read.csv("markergene_compara/mira_sporo_somule_adult_compare_Tegument_markers_30.csv") #import the marker data from somule papaer
markergenesInGO <- filter(unNestedGO, genes %in%  c(myMarkers$sporocyst_teg.gene))
write.csv(x=markergenesInGO, file="markergene_compara/tegumentMarkersInGO.csv") #save this as a csv
```


